# Generated by Django 2.2b1 on 2019-03-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pronac',
            field=models.IntegerField(unique=True),
        ),
    ]
