# Generated by Django 2.2b1 on 2019-03-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stage',
            new_name='description',
        ),
    ]
