# Generated by Django 2.2b1 on 2019-03-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190314_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='reason',
        ),
        migrations.AddField(
            model_name='metric',
            name='value',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
