image: docker:stable

stages:
  - tests
  - build-requirements
  - build-api

services:
  - docker:dind

tests:
  stage: tests
  before_script:
    - apk add py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose -f docker/docker-compose-offline.yml up -d
    - docker exec -t docker_django_1 inv test

build requirements:
  stage: build-requirements
  variables:
    SALICML_PROD_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/salicml/requirements:latest
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/Dockerfile.base -t $SALICML_PROD_RELEASE_IMAGE .
    - docker push $SALICML_PROD_RELEASE_IMAGE
  only:
    - master

build api:
  stage: build-api
  variables:
    SALICML_PROD_RELEASE_IMAGE: $CI_REGISTRY_IMAGE/salicml/api:latest
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -f docker/Dockerfile -t $SALICML_PROD_RELEASE_IMAGE .
    - docker push $SALICML_PROD_RELEASE_IMAGE
  only:
    - master