# Generated by Django 2.1.5 on 2019-02-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projetos'},
        ),
    ]
