version: '2'

services:
  postgres:
    image: postgres
    env_file:
      - ../etc/env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../etc/scripts/multiple-postgresql:/docker-entrypoint-initdb.d/

  django:
    image: salicml/api:latest
    links:
      - "salic_db"
    build:
       context: ../
       dockerfile: ./docker/Dockerfile
    command: inv make migrate run
    env_file:
      - ../etc/env/db.env # salic_db
      - ../etc/env/postgres.env
    volumes:
      - ../src:/src
      - ../data:/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres

  salic_db:
    image: lappis/openconnect-globalprotect
    env_file:
      - ../etc/env/vpn.env
    ports:
      - "9000:1435"
    privileged: true
    cap_add:
      - NET-ADMIN

volumes:
  postgres_data:
