version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    volumes:
      - ../data/nginx:/etc/nginx/conf.d
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - django
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  postgres:
    image: postgres
    env_file:
      - ../etc/env/deploy.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  django:
    image: registry.gitlab.com/lappis-unb/services/salic-ml/salicml/api:latest
    command: inv make migrate run
    env_file:
      - ../etc/env/db.env
      - ../etc/env/deploy.env
    volumes:
      - ../data:/data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - salic_db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  salic_db:
    image: lappis/openconnect-globalprotect
    env_file:
      - ../etc/env/vpn.env
    ports:
      - "9000:1435"
    privileged: true
    cap_add:
      - NET-ADMIN
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
  
volumes:
  postgres_data:
