# Generated by Django 2.2rc1 on 2019-03-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialindicator',
            options={},
        ),
        migrations.AlterModelOptions(
            name='indicator',
            options={},
        ),
    ]
