# Generated by Django 2.1.7 on 2019-04-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pronac',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
