# Generated by Django 2.1.7 on 2019-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190328_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AlterField(
            model_name='project',
            name='pronac',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
