# Generated by Django 2.2.1 on 2019-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190412_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
