# Generated by Django 2.1.7 on 2019-04-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20190410_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissibilityIndicator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('analysis.indicator',),
        ),
    ]
