# Generated by Django 2.2 on 2019-04-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_admissibilityindicator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissibilityIndicator',
        ),
    ]
